apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user.api
  template:
    metadata:
      labels:
        app: user.api
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: userapi
        image: csmbackend.azurecr.io:443/userapi:latest
        imagePullPolicy: Always
        resources:   
        env:
          - name: ConnectionStrings.DefaultConnection
            value: "Server=localhost;Port=5432;Database=UserDb;User Id=admin;Password=Admin@1234;"  
          - name: EventBusSettings.HostAddress
            value: "amqp://guest:guest@rabbitmq:5672"
          - name: JwtConfig.ValidIssuer 
            value: "cloudstoremalawi.com"
          - name: JwtConfig.ValidAudience
            value: "cloudstoremalawi.com"
          - name: JwtConfig.FacebookAudience
            value: "754381865748304"
          - name: JwtConfig.Secret 
            value: "770A8A65DA156D24770A8A65DA156D24"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user.api
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80